version: "{branch} #{build}"

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x64

build:
  parallel: true

build_script:
  - cmake -A %PLATFORM%
  - cmake --build . --config Debug
  - cmake --build . --config Release

test_script:
  - ctest --output-on-failure -C Debug
  - ctest --output-on-failure -C Release
